on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install build tools
        uses: jdx/mise-action@v3
        env:
          MISE_GITHUB_TOKEN: ""

      - name: Build
        run: mvn -B verify
